language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib --global install 2

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due
- BOARD=genuino101
- BOARD=zero

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done

notifications:
  flowdock:
    # main flow
    - secure: "N1d7e0CiJb3/wvNxP3Faw1wdSTbGEerrSoByC+jEnfx8+W1P5pU/l9ptTl/LDOElQpFojicPz/Fk12Jr+uiJTnRYkVNxzI391qvOhMe3p26/n8Km//LvcXAhNLM9akighX+HavDLauxO+9NGB76W02Ycr+0a530S3e0RPn7AXzC+2p330V64ffmKqU2UgHfoV0q04DcjMnxwX30k8uJEbEqPkraW3en2XHM9p0jSXxacVOaxrw452H+Rs640wF68b7Srh9Du34D/6x7wkAvUqru4Hss9lPaOtVu7E3JjeebPXbWrBhG7sAF/tBOTH3JimQqS6irE/dswdJc0lVf/WJYorl9W5EXl1dp2x1dbuReDmAi9f4ytRLwkxVNgf3QJJQ7GAqO5+hG4RoaJ8z2l0gUNXv+ZyDr1N8sLzTXwM9WQGiGR9ez5M5IfP5UOYN1r8DILkrBo+0jnPNX8NChPzd75Xdw1bGvz3HnB67nH32O1OdBhJWo5MrDW4NS/y5Z7/VfVTzWI4gR7ixgiuqy7jVMK9wHf1csDOXNXU2tvj8CvMqV2h349qwnqlKK6IfJ58S/0er1sgdkPzUv5f80o93AUBSS55ZdPXjxu0FNR72I9qtZsXv1ZDFwlW8HoDp6WzL6WdXRWEpgYbLAFyBf83SZSCwVEV3L2K+o58hpJyEk="
    # software team
    - secure: "nTAD9kJw3jK+3RCwVoaaN+fH43mLPn4rUwboVEKwNczu2z+yQtHJKkcfsdM3Kn5eGcqNSibU8vg1W9XgmUOXIa5dHK3o2gmO4TcVUQ8luFO9QXVoUDAZhum+3OQA3eq37JsCgubreogI5hms1MAiLS3qDBX2QstYUDBeO7+0uwFUu3Qil5PI2hXp43N4AdQtFQR9YuWDhVh0NO5ARLLkPE++PxoRqcwCe73FF8IEoUuP4GaIJYkK2tufkhX9Icu8xinTvIvfk3CgFT3fh5JS+9wtJ/V8iVDW/dPFi8UnZ26LXWv417SCLIFQvPYaUBqFerJZzLLYFS2vlo683havvH1BRejwcwShC/OLLDnb4/WSNWicuF4G0V7UGM/VmHeqeOY0lONSycMH0F/nVWSdGaEtY1wmC3aIWow40fz4U17wEIoAzmY766fsPeFeju1BGBae7dNI8bnr8m8vZEq0tukhrnzNuXnwDu4g+I0szcFD+1t3mxe1b80AQtCAXD6uxtfFPpTX49WK4faosGvUsjAuloht0JCUvPbUhUNG99Fa9ZiD9x0DcZD7lhd1YjUXwVMQq9ir/Hil/eO/FwqN5GfT8RKZOwk8GZhY/ZvhxoRWLVzJB5l/8yHcFznkKHE/iYJiZvZFa64PnLY3UyVEAqZIQnMg4JtjiMqsRdhHhEU="
